const beginnerWords = [
  {id: 1, wordEng: "hello", wordUA: "привіт", transcription: "[həˈləʊ]"},
  {id: 2, wordEng: "thank you", wordUA: "дякую", transcription: "[θæŋk juː]"},
  {id: 3, wordEng: "please", wordUA: "будь ласка (прохання)", transcription: "[pliːz]"},
  {id: 4, wordEng: "you're welcome", wordUA: "будь ласка (відповідь)", transcription: "[jʊə ˈwelkəm]"},
  {id: 5, wordEng: "excuse me", wordUA: "перепрошую", transcription: "[ɪkˈskjuːz miː]"},
  {id: 6, wordEng: "sorry", wordUA: "вибачте", transcription: "[ˈsɒri]"},
  {id: 7, wordEng: "yes", wordUA: "так", transcription: "[jes]"},
  {id: 8, wordEng: "no", wordUA: "ні", transcription: "[nəʊ]"},
  {id: 9, wordEng: "maybe", wordUA: "можливо", transcription: "[ˈmeɪbi]"},
  {id: 10, wordEng: "goodbye", wordUA: "до побачення", transcription: "[ˌɡʊdˈbaɪ]"},
  {id: 11, wordEng: "help", wordUA: "допомога", transcription: "[help]"},
  {id: 12, wordEng: "I don't know", wordUA: "я не знаю", transcription: "[aɪ dəʊnt nəʊ]"},
  {id: 13, wordEng: "I understand", wordUA: "я розумію", transcription: "[aɪ ˌʌndəˈstænd]"},
  {id: 14, wordEng: "I don't understand", wordUA: "я не розумію", transcription: "[aɪ dəʊnt ˌʌndəˈstænd]"},
  {id: 15, wordEng: "what", wordUA: "що / який", transcription: "[wɒt]"},
  {id: 16, wordEng: "where", wordUA: "де / куди", transcription: "[weə]"},
  {id: 17, wordEng: "when", wordUA: "коли", transcription: "[wen]"},
  {id: 18, wordEng: "why", wordUA: "чому", transcription: "[waɪ]"},
  {id: 19, wordEng: "who", wordUA: "хто", transcription: "[huː]"},
  {id: 20, wordEng: "how", wordUA: "як", transcription: "[haʊ]"},
  {id: 21, wordEng: "how much", wordUA: "скільки (ціна)", transcription: "[haʊ mʌtʃ]"},
  {id: 22, wordEng: "how many", wordUA: "скільки (кількість)", transcription: "[haʊ ˈmeni]"},
  {id: 23, wordEng: "what time is it", wordUA: "котра година", transcription: "[wɒt taɪm ɪz ɪt]"},
  {id: 24, wordEng: "where is", wordUA: "де знаходиться", transcription: "[weə ɪz]"},
  {id: 25, wordEng: "I need", wordUA: "мені потрібно", transcription: "[aɪ niːd]"},
  {id: 26, wordEng: "I want", wordUA: "я хочу", transcription: "[aɪ wɒnt]"},
  {id: 27, wordEng: "I'd like", wordUA: "я б хотів", transcription: "[aɪd laɪk]"},
  {id: 28, wordEng: "can I", wordUA: "можна мені / чи можу я", transcription: "[kæn aɪ]"},
  {id: 29, wordEng: "could you", wordUA: "не могли б ви", transcription: "[kʊd juː]"},
  {id: 30, wordEng: "give me", wordUA: "дайте мені", transcription: "[ɡɪv miː]"},
  {id: 31, wordEng: "show me", wordUA: "покажіть мені", transcription: "[ʃəʊ miː]"},
  {id: 32, wordEng: "wait", wordUA: "чекати", transcription: "[weɪt]"},
  {id: 33, wordEng: "look", wordUA: "дивитися", transcription: "[lʊk]"},
  {id: 34, wordEng: "listen", wordUA: "слухати", transcription: "[ˈlɪsn]"},
  {id: 35, wordEng: "stop", wordUA: "зупинитися", transcription: "[stɒp]"},
  {id: 36, wordEng: "go", wordUA: "йти / їхати", transcription: "[ɡəʊ]"},
  {id: 37, wordEng: "come", wordUA: "приходити", transcription: "[kʌm]"},
  {id: 38, wordEng: "eat", wordUA: "їсти", transcription: "[iːt]"},
  {id: 39, wordEng: "drink", wordUA: "пити", transcription: "[drɪŋk]"},
  {id: 40, wordEng: "sleep", wordUA: "спати", transcription: "[sliːp]"},
  {id: 41, wordEng: "buy", wordUA: "купувати", transcription: "[baɪ]"},
  {id: 42, wordEng: "sell", wordUA: "продавати", transcription: "[sel]"},
  {id: 43, wordEng: "open", wordUA: "відчинено", transcription: "[ˈəʊpən]"},
  {id: 44, wordEng: "closed", wordUA: "зачинено", transcription: "[kləʊzd]"},
  {id: 45, wordEng: "push", wordUA: "від себе", transcription: "[pʊʃ]"},
  {id: 46, wordEng: "pull", wordUA: "на себе", transcription: "[pʊl]"},
  {id: 47, wordEng: "today", wordUA: "сьогодні", transcription: "[təˈdeɪ]"},
  {id: 48, wordEng: "tomorrow", wordUA: "завтра", transcription: "[təˈmɒrəʊ]"},
  {id: 49, wordEng: "yesterday", wordUA: "вчора", transcription: "[ˈjestədeɪ]"},
  {id: 50, wordEng: "now", wordUA: "зараз", transcription: "[naʊ]"},
  {id: 51, wordEng: "later", wordUA: "пізніше", transcription: "[ˈleɪtə]"},
  {id: 52, wordEng: "always", wordUA: "завжди", transcription: "[ˈɔːlweɪz]"},
  {id: 53, wordEng: "never", wordUA: "ніколи", transcription: "[ˈnevə]"},
  {id: 54, wordEng: "often", wordUA: "часто", transcription: "[ˈɒfn]"},
  {id: 55, wordEng: "sometimes", wordUA: "інколи", transcription: "[ˈsʌmtaɪmz]"},
  {id: 56, wordEng: "good", wordUA: "добре / хороший", transcription: "[ɡʊd]"},
  {id: 57, wordEng: "bad", wordUA: "погано / поганий", transcription: "[bæd]"},
  {id: 58, wordEng: "hot", wordUA: "гарячий / жарко", transcription: "[hɒt]"},
  {id: 59, wordEng: "cold", wordUA: "холодний / холодно", transcription: "[kəʊld]"},
  {id: 60, wordEng: "big", wordUA: "великий", transcription: "[bɪɡ]"},
  {id: 61, wordEng: "small", wordUA: "маленький", transcription: "[smɔːl]"},
  {id: 62, wordEng: "fast", wordUA: "швидко", transcription: "[fɑːst]"},
  {id: 63, wordEng: "slow", wordUA: "повільно", transcription: "[sləʊ]"},
  {id: 64, wordEng: "easy", wordUA: "легко", transcription: "[ˈiːzi]"},
  {id: 65, wordEng: "difficult", wordUA: "важко", transcription: "[ˈdɪfɪkəlt]"},
  {id: 66, wordEng: "cheap", wordUA: "дешево", transcription: "[tʃiːp]"},
  {id: 67, wordEng: "expensive", wordUA: "дорого", transcription: "[ɪkˈspensɪv]"},
  {id: 68, wordEng: "new", wordUA: "новий", transcription: "[njuː]"},
  {id: 69, wordEng: "old", wordUA: "старий", transcription: "[əʊld]"},
  {id: 70, wordEng: "beautiful", wordUA: "красивий", transcription: "[ˈbjuːtɪfl]"},
  {id: 71, wordEng: "happy", wordUA: "щасливий", transcription: "[ˈhæpi]"},
  {id: 72, wordEng: "sad", wordUA: "сумний", transcription: "[sæd]"},
  {id: 73, wordEng: "tired", wordUA: "втомлений", transcription: "[ˈtaɪəd]"},
  {id: 74, wordEng: "hungry", wordUA: "голодний", transcription: "[ˈhʌŋɡri]"},
  {id: 75, wordEng: "thirsty", wordUA: "хоче пити", transcription: "[ˈθɜːsti]"},
  {id: 76, wordEng: "ready", wordUA: "готовий", transcription: "[ˈredi]"},
  {id: 77, wordEng: "here", wordUA: "тут", transcription: "[hɪə]"},
  {id: 78, wordEng: "there", wordUA: "там", transcription: "[ðeə]"},
  {id: 79, wordEng: "left", wordUA: "ліворуч", transcription: "[left]"},
  {id: 80, wordEng: "right", wordUA: "праворуч / правильно", transcription: "[raɪt]"},
  {id: 81, wordEng: "straight", wordUA: "прямо", transcription: "[streɪt]"},
  {id: 82, wordEng: "early", wordUA: "рано", transcription: "[ˈɜːli]"},
  {id: 83, wordEng: "late", wordUA: "пізно", transcription: "[leɪt]"},
  {id: 84, wordEng: "very", wordUA: "дуже", transcription: "[ˈveri]"},
  {id: 85, wordEng: "too", wordUA: "занадто / також", transcription: "[tuː]"},
  {id: 86, wordEng: "enough", wordUA: "достатньо", transcription: "[ɪˈnʌf]"},
  {id: 87, wordEng: "and", wordUA: "і / та", transcription: "[ænd]"},
  {id: 88, wordEng: "but", wordUA: "але", transcription: "[bʌt]"},
  {id: 89, wordEng: "or", wordUA: "або", transcription: "[ɔː]"},
  {id: 90, wordEng: "because", wordUA: "тому що", transcription: "[bɪˈkəz]"},
  {id: 91, wordEng: "with", wordUA: "з", transcription: "[wɪð]"},
  {id: 92, wordEng: "without", wordUA: "без", transcription: "[wɪˈðaʊt]"},
  {id: 93, wordEng: "about", wordUA: "про", transcription: "[əˈbaʊt]"},
  {id: 94, wordEng: "for", wordUA: "для", transcription: "[fɔː]"},
  {id: 95, wordEng: "from", wordUA: "від / з", transcription: "[frəm]"},
  {id: 96, wordEng: "to", wordUA: "до / напрямок", transcription: "[tuː]"},
  {id: 97, wordEng: "at", wordUA: "в (точці) / біля", transcription: "[æt]"},
  {id: 98, wordEng: "on", wordUA: "на", transcription: "[ɒn]"},
  {id: 99, wordEng: "in", wordUA: "в (всередині)", transcription: "[ɪn]"},
  {id: 100, wordEng: "by the way", wordUA: "до речі", transcription: "[baɪ ðə weɪ]"}
];

const intermediateWords = [
  {id: 101, wordEng: "although", wordUA: "хоча", transcription: "[ɔːlˈðəʊ]"},
  {id: 102, wordEng: "however", wordUA: "проте / однак", transcription: "[haʊˈevə]"},
  {id: 103, wordEng: "therefore", wordUA: "отже / тому", transcription: "[ˈðeəfɔː]"},
  {id: 104, wordEng: "instead", wordUA: "замість цього", transcription: "[ɪnˈsted]"},
  {id: 105, wordEng: "perhaps", wordUA: "можливо / мабуть", transcription: "[pəˈhæps]"},
  {id: 106, wordEng: "probably", wordUA: "ймовірно", transcription: "[ˈprɒbəbli]"},
  {id: 107, wordEng: "actually", wordUA: "насправді", transcription: "[ˈæktʃuəli]"},
  {id: 108, wordEng: "especially", wordUA: "особливо", transcription: "[ɪˈspeʃəli]"},
  {id: 109, wordEng: "experience", wordUA: "досвід", transcription: "[ɪkˈspɪəriəns]"},
  {id: 110, wordEng: "opportunity", wordUA: "можливість", transcription: "[ˌɒpəˈtjuːnəti]"},
  {id: 111, wordEng: "decision", wordUA: "рішення", transcription: "[dɪˈsɪʒn]"},
  {id: 112, wordEng: "agreement", wordUA: "угода / згода", transcription: "[əˈɡriːmənt]"},
  {id: 113, wordEng: "development", wordUA: "розвиток", transcription: "[dɪˈveləpmənt]"},
  {id: 114, wordEng: "government", wordUA: "уряд", transcription: "[ˈɡʌvənmənt]"},
  {id: 115, wordEng: "knowledge", wordUA: "знання", transcription: "[ˈnɒlɪdʒ]"},
  {id: 116, wordEng: "environment", wordUA: "середовище", transcription: "[ɪnˈvaɪrənmənt]"},
  {id: 117, wordEng: "society", wordUA: "суспільство", transcription: "[səˈsaɪəti]"},
  {id: 118, wordEng: "believe", wordUA: "вірити", transcription: "[bɪˈliːv]"},
  {id: 119, wordEng: "remember", wordUA: "пам'ятати", transcription: "[rɪˈmembə]"},
  {id: 120, wordEng: "forget", wordUA: "забувати", transcription: "[fəˈɡet]"},
  {id: 121, wordEng: "improve", wordUA: "покращувати", transcription: "[ɪmˈpruːv]"},
  {id: 122, wordEng: "increase", wordUA: "збільшувати", transcription: "[ɪnˈkriːs]"},
  {id: 123, wordEng: "decrease", wordUA: "зменшувати", transcription: "[dɪˈkriːs]"},
  {id: 124, wordEng: "provide", wordUA: "надавати / забезпечувати", transcription: "[prəˈvaɪd]"},
  {id: 125, wordEng: "receive", wordUA: "отримувати", transcription: "[rɪˈsiːv]"},
  {id: 126, wordEng: "describe", wordUA: "описувати", transcription: "[dɪˈskraɪb]"},
  {id: 127, wordEng: "explain", wordUA: "пояснювати", transcription: "[ɪkˈspleɪn]"},
  {id: 128, wordEng: "imagine", wordUA: "уявляти", transcription: "[ɪˈmædʒɪn]"},
  {id: 129, wordEng: "suggest", wordUA: "пропонувати / радити", transcription: "[səˈdʒest]"},
  {id: 130, wordEng: "discuss", wordUA: "обговорювати", transcription: "[dɪˈskʌs]"},
  {id: 131, wordEng: "happen", wordUA: "траплятися", transcription: "[ˈhæpən]"},
  {id: 132, wordEng: "expect", wordUA: "очікувати", transcription: "[ɪkˈspekt]"},
  {id: 133, wordEng: "suppose", wordUA: "припускати", transcription: "[səˈpəʊz]"},
  {id: 134, wordEng: "realize", wordUA: "усвідомлювати", transcription: "[ˈrɪəlaɪz]"},
  {id: 135, wordEng: "complain", wordUA: "скаржитися", transcription: "[kəmˈpleɪn]"},
  {id: 136, wordEng: "avoid", wordUA: "уникати", transcription: "[əˈvɔɪd]"},
  {id: 137, wordEng: "depend", wordUA: "залежати", transcription: "[dɪˈpend]"},
  {id: 138, wordEng: "achieve", wordUA: "досягати", transcription: "[əˈtʃiːv]"},
  {id: 139, wordEng: "refuse", wordUA: "відмовлятися", transcription: "[rɪˈfjuːz]"},
  {id: 140, wordEng: "accept", wordUA: "приймати", transcription: "[əkˈsept]"},
  {id: 141, wordEng: "useful", wordUA: "корисний", transcription: "[ˈjuːsfl]"},
  {id: 142, wordEng: "useless", wordUA: "марний", transcription: "[ˈjuːsləs]"},
  {id: 143, wordEng: "necessary", wordUA: "необхідний", transcription: "[ˈnesəsəri]"},
  {id: 144, wordEng: "possible", wordUA: "можливий", transcription: "[ˈpɒsəbl]"},
  {id: 145, wordEng: "impossible", wordUA: "неможливий", transcription: "[ɪmˈpɒsəbl]"},
  {id: 146, wordEng: "available", wordUA: "доступний", transcription: "[əˈveɪləbl]"},
  {id: 147, wordEng: "successful", wordUA: "успішний", transcription: "[səkˈsesfl]"},
  {id: 148, wordEng: "responsible", wordUA: "відповідальний", transcription: "[rɪˈspɒnsəbl]"},
  {id: 149, wordEng: "various", wordUA: "різноманітні", transcription: "[ˈveəriəs]"},
  {id: 150, wordEng: "common", wordUA: "спільний / звичайний", transcription: "[ˈkɒmən]"},
  {id: 151, wordEng: "similar", wordUA: "схожий", transcription: "[ˈsɪmələ]"},
  {id: 152, wordEng: "different", wordUA: "інший / різний", transcription: "[ˈdɪfrənt]"},
  {id: 153, wordEng: "certain", wordUA: "певний / впевнений", transcription: "[ˈsɜːtn]"},
  {id: 154, wordEng: "careful", wordUA: "обережний", transcription: "[ˈkeəfl]"},
  {id: 155, wordEng: "dangerous", wordUA: "небезпечний", transcription: "[ˈdeɪndʒərəs]"},
  {id: 156, wordEng: "famous", wordUA: "відомий", transcription: "[ˈfeɪməs]"},
  {id: 157, wordEng: "lucky", wordUA: "удачливий", transcription: "[ˈlʌki]"},
  {id: 158, wordEng: "patient", wordUA: "терплячий", transcription: "[ˈpeɪʃnt]"},
  {id: 159, wordEng: "polite", wordUA: "ввічливий", transcription: "[pəˈlaɪt]"},
  {id: 160, wordEng: "rude", wordUA: "грубий", transcription: "[ruːd]"},
  {id: 161, wordEng: "suddenly", wordUA: "раптом", transcription: "[ˈsʌdənli]"},
  {id: 162, wordEng: "immediately", wordUA: "негайно", transcription: "[ɪˈmiːdiətli]"},
  {id: 163, wordEng: "recently", wordUA: "нещодавно", transcription: "[ˈriːsntli]"},
  {id: 164, wordEng: "completely", wordUA: "повністю", transcription: "[kəmˈpliːtli]"},
  {id: 165, wordEng: "finally", wordUA: "зрештою", transcription: "[ˈfaɪnəli]"},
  {id: 166, wordEng: "quickly", wordUA: "швидко", transcription: "[ˈkwɪkli]"},
  {id: 167, wordEng: "slowly", wordUA: "повільно", transcription: "[ˈsləʊli]"},
  {id: 168, wordEng: "hardly", wordUA: "навряд чи", transcription: "[ˈhɑːdli]"},
  {id: 169, wordEng: "enough", wordUA: "достатньо", transcription: "[ɪˈnʌf]"},
  {id: 170, wordEng: "already", wordUA: "вже", transcription: "[ɔːlˈredi]"},
  {id: 171, wordEng: "still", wordUA: "все ще", transcription: "[stɪl]"},
  {id: 172, wordEng: "yet", wordUA: "ще (в запереченнях)", transcription: "[jet]"},
  {id: 173, wordEng: "since", wordUA: "з того часу як", transcription: "[sɪns]"},
  {id: 174, wordEng: "while", wordUA: "поки / в той час як", transcription: "[waɪl]"},
  {id: 175, wordEng: "during", wordUA: "протягом", transcription: "[ˈdjʊərɪŋ]"},
  {id: 176, wordEng: "between", wordUA: "між (двома)", transcription: "[bɪˈtwiːn]"},
  {id: 177, wordEng: "among", wordUA: "серед (багатьох)", transcription: "[əˈmʌŋ]"},
  {id: 178, wordEng: "above", wordUA: "над", transcription: "[əˈbʌv]"},
  {id: 179, wordEng: "below", wordUA: "під / нижче", transcription: "[bɪˈləʊ]"},
  {id: 180, wordEng: "against", wordUA: "проти", transcription: "[əˈɡenst]"},
  {id: 181, wordEng: "reason", wordUA: "причина", transcription: "[ˈriːzn]"},
  {id: 182, wordEng: "result", wordUA: "результат", transcription: "[rɪˈzʌlt]"},
  {id: 183, wordEng: "purpose", wordUA: "мета", transcription: "[ˈpɜːpəs]"},
  {id: 184, wordEng: "opinion", wordUA: "думка", transcription: "[əˈpɪnjən]"},
  {id: 185, wordEng: "advice", wordUA: "порада", transcription: "[ədˈvaɪs]"},
  {id: 186, wordEng: "suggestion", wordUA: "пропозиція", transcription: "[səˈdʒestʃən]"},
  {id: 187, wordEng: "solution", wordUA: "рішення (проблеми)", transcription: "[səˈluːʃn]"},
  {id: 188, wordEng: "problem", wordUA: "проблема", transcription: "[ˈprɒbləm]"},
  {id: 189, wordEng: "difference", wordUA: "різниця", transcription: "[ˈdɪfrəns]"},
  {id: 190, wordEng: "advantage", wordUA: "перевага", transcription: "[ədˈvɑːntɪdʒ]"},
  {id: 191, wordEng: "disadvantage", wordUA: "недолік", transcription: "[ˌdɪsədˈvɑːntɪdʒ]"},
  {id: 192, wordEng: "ability", wordUA: "здатність", transcription: "[əˈbɪləti]"},
  {id: 193, wordEng: "behavior", wordUA: "поведінка", transcription: "[bɪˈheɪvjə]"},
  {id: 194, wordEng: "celebration", wordUA: "святкування", transcription: "[ˌselɪˈbreɪʃn]"},
  {id: 195, wordEng: "condition", wordUA: "умова / стан", transcription: "[kənˈdɪʃn]"},
  {id: 196, wordEng: "education", wordUA: "освіта", transcription: "[ˌedʒuˈkeɪʃn]"},
  {id: 197, wordEng: "health", wordUA: "здоров'я", transcription: "[helθ]"},
  {id: 198, wordEng: "island", wordUA: "острів", transcription: "[ˈaɪlənd]"},
  {id: 199, wordEng: "journey", wordUA: "подорож", transcription: "[ˈdʒɜːni]"},
  {id: 200, wordEng: "neighborhood", wordUA: "сусідство / район", transcription: "[ˈneɪbəhʊd]"}
];

const advancedWords = [
  {id: 201, wordEng: "ambiguous", wordUA: "двозначний / неясний", transcription: "[æmˈbɪɡjuəs]"},
  {id: 202, wordEng: "comprehensive", wordUA: "вичерпний / всебічний", transcription: "[ˌkɒmprɪˈhensɪv]"},
  {id: 203, wordEng: "consequence", wordUA: "наслідок", transcription: "[ˈkɒnsɪkwəns]"},
  {id: 204, wordEng: "controversial", wordUA: "суперечливий", transcription: "[ˌkɒntrəˈvɜːʃl]"},
  {id: 205, wordEng: "crucial", wordUA: "вирішальний / критичний", transcription: "[ˈkruːʃl]"},
  {id: 206, wordEng: "distinction", wordUA: "відмінність / розрізнення", transcription: "[dɪˈstɪŋkʃn]"},
  {id: 207, wordEng: "elaborate", wordUA: "детально розробляти", transcription: "[ɪˈlæbərət]"},
  {id: 208, wordEng: "hypothesis", wordUA: "гіпотеза", transcription: "[haɪˈpɒθəsɪs]"},
  {id: 209, wordEng: "implement", wordUA: "впроваджувати", transcription: "[ˈɪmplɪment]"},
  {id: 210, wordEng: "inevitable", wordUA: "неминучий", transcription: "[ɪnˈevɪtəbl]"},
  {id: 211, wordEng: "insight", wordUA: "розуміння суті / осяяння", transcription: "[ˈɪnsaɪt]"},
  {id: 212, wordEng: "justify", wordUA: "виправдовувати / обґрунтовувати", transcription: "[ˈdʒʌstɪfaɪ]"},
  {id: 213, wordEng: "obvious", wordUA: "очевидний", transcription: "[ˈɒbviəs]"},
  {id: 214, wordEng: "perception", wordUA: "сприйняття", transcription: "[pəˈsepʃn]"},
  {id: 215, wordEng: "redundant", wordUA: "надлишковий / зайвий", transcription: "[rɪˈdʌndənt]"},
  {id: 216, wordEng: "subtle", wordUA: "тонкий / ледь помітний", transcription: "[ˈsʌtl]"},
  {id: 217, wordEng: "sustainable", wordUA: "сталий / життєздатний", transcription: "[səˈsteɪnəbl]"},
  {id: 218, wordEng: "vague", wordUA: "нечіткий / розпливчастий", transcription: "[veɪɡ]"},
  {id: 219, wordEng: "vulnerable", wordUA: "вразливий", transcription: "[ˈvʌlnərəbl]"},
  {id: 220, wordEng: "acknowledge", wordUA: "визнавати / підтверджувати", transcription: "[əkˈnɒlɪdʒ]"},
  {id: 221, wordEng: "acquire", wordUA: "набувати / здобувати", transcription: "[əˈkwaɪə]"},
  {id: 222, wordEng: "advocate", wordUA: "виступати на захист", transcription: "[ˈædvəkeɪt]"},
  {id: 223, wordEng: "allocate", wordUA: "розподіляти (ресурси)", transcription: "[ˈæləkeɪt]"},
  {id: 224, wordEng: "anticipate", wordUA: "передбачати", transcription: "[ænˈtɪsɪpeɪt]"},
  {id: 225, wordEng: "assert", wordUA: "стверджувати", transcription: "[əˈsɜːt]"},
  {id: 226, wordEng: "cease", wordUA: "припиняти", transcription: "[siːs]"},
  {id: 227, wordEng: "coincide", wordUA: "збігатися", transcription: "[ˌkəʊɪnˈsaɪd]"},
  {id: 228, wordEng: "compel", wordUA: "примушувати", transcription: "[kəmˈpel]"},
  {id: 229, wordEng: "concede", wordUA: "поступатися / визнавати поразку", transcription: "[kənˈsiːd]"},
  {id: 230, wordEng: "deduce", wordUA: "робити висновок", transcription: "[dɪˈdjuːs]"},
  {id: 231, wordEng: "depict", wordUA: "зображувати", transcription: "[dɪˈpɪkt]"},
  {id: 232, wordEng: "deteriorate", wordUA: "погіршуватися", transcription: "[dɪˈtɪəriəreɪt]"},
  {id: 233, wordEng: "disrupt", wordUA: "підривати / порушувати", transcription: "[dɪsˈrʌpt]"},
  {id: 234, wordEng: "eliminate", wordUA: "усувати / ліквідувати", transcription: "[ɪˈlɪmɪneɪt]"},
  {id: 235, wordEng: "emphasize", wordUA: "наголошувати", transcription: "[ˈemfəsaɪz]"},
  {id: 236, wordEng: "encounter", wordUA: "стикатися / несподівано зустріти", transcription: "[ɪnˈkaʊntə]"},
  {id: 237, wordEng: "enhance", wordUA: "посилювати / покращувати", transcription: "[ɪnˈhɑːns]"},
  {id: 238, wordEng: "evaluate", wordUA: "оцінювати", transcription: "[ɪˈvæljueɪt]"},
  {id: 239, wordEng: "exacerbate", wordUA: "загострювати / погіршувати", transcription: "[ɪɡˈzæsəbeɪt]"},
  {id: 240, wordEng: "exceed", wordUA: "перевищувати", transcription: "[ɪkˈsiːd]"},
  {id: 241, wordEng: "facilitate", wordUA: "сприяти / полегшувати", transcription: "[fəˈsɪlɪteɪt]"},
  {id: 242, wordEng: "fluctuate", wordUA: "коливатися", transcription: "[ˈflʌktʃueɪt]"},
  {id: 243, wordEng: "foster", wordUA: "сприяти розвитку / виховувати", transcription: "[ˈfɒstə]"},
  {id: 244, wordEng: "hinder", wordUA: "перешкоджати", transcription: "[ˈhɪndə]"},
  {id: 245, wordEng: "infer", wordUA: "робити висновок", transcription: "[ɪnˈfɜː]"},
  {id: 246, wordEng: "inhibit", wordUA: "гальмувати / пригнічувати", transcription: "[ɪnˈhɪbɪt]"},
  {id: 247, wordEng: "initiate", wordUA: "започатковувати", transcription: "[ɪˈnɪʃieɪt]"},
  {id: 248, wordEng: "integrate", wordUA: "об'єднувати", transcription: "[ˈɪntɪɡreɪt]"},
  {id: 249, wordEng: "interpret", wordUA: "тлумачити", transcription: "[ɪnˈtɜːprɪt]"},
  {id: 250, wordEng: "manipulate", wordUA: "маніпулювати", transcription: "[məˈnɪpjuleɪt]"},
  {id: 251, wordEng: "modify", wordUA: "змінювати / модифікувати", transcription: "[ˈmɒdɪfaɪ]"},
  {id: 252, wordEng: "notwithstanding", wordUA: "незважаючи на", transcription: "[ˌnɒtwɪθˈstændɪŋ]"},
  {id: 253, wordEng: "obscure", wordUA: "робити неясним / приховувати", transcription: "[əbˈskjʊə]"},
  {id: 254, wordEng: "overlook", wordUA: "не помічати / пропускати", transcription: "[ˌəʊvəˈlʊk]"},
  {id: 255, wordEng: "perceive", wordUA: "сприймати / відчувати", transcription: "[pəˈsiːv]"},
  {id: 256, wordEng: "persist", wordUA: "наполегливо продовжувати", transcription: "[pəˈsɪst]"},
  {id: 257, wordEng: "precede", wordUA: "передувати", transcription: "[prɪˈsiːd]"},
  {id: 258, wordEng: "prohibit", wordUA: "забороняти", transcription: "[prəˈhɪbɪt]"},
  {id: 259, wordEng: "pursue", wordUA: "переслідувати / домагатися", transcription: "[pəˈsjuː]"},
  {id: 260, wordEng: "reconcile", wordUA: "примирити / узгодити", transcription: "[ˈrekənsaɪl]"},
  {id: 261, wordEng: "reinforce", wordUA: "підсилювати", transcription: "[ˌriːɪnˈfɔːs]"},
  {id: 262, wordEng: "reluctant", wordUA: "неохочий", transcription: "[rɪˈlʌktənt]"},
  {id: 263, wordEng: "resemble", wordUA: "бути схожим на", transcription: "[rɪˈzembl]"},
  {id: 264, wordEng: "retain", wordUA: "утримувати / зберігати", transcription: "[rɪˈteɪn]"},
  {id: 265, wordEng: "reveal", wordUA: "виявляти / розкривати", transcription: "[rɪˈviːl]"},
  {id: 266, wordEng: "scrutinize", wordUA: "ретельно вивчати", transcription: "[ˈskruːtənaɪz]"},
  {id: 267, wordEng: "simultaneous", wordUA: "одночасний", transcription: "[ˌsɪmlˈteɪniəs]"},
  {id: 268, wordEng: "speculate", wordUA: "міркувати / робити припущення", transcription: "[ˈspekjuleɪt]"},
  {id: 269, wordEng: "subsequent", wordUA: "наступний / подальший", transcription: "[ˈsʌbsɪkwənt]"},
  {id: 270, wordEng: "sufficient", wordUA: "достатній", transcription: "[səˈfɪʃnt]"},
  {id: 271, wordEng: "surpass", wordUA: "перевершувати", transcription: "[səˈpɑːs]"},
  {id: 272, wordEng: "sustain", wordUA: "підтримувати", transcription: "[səˈsteɪn]"},
  {id: 273, wordEng: "tedious", wordUA: "нудний / виснажливий", transcription: "[ˈtiːdiəs]"},
  {id: 274, wordEng: "thrive", wordUA: "процвітати", transcription: "[θraɪv]"},
  {id: 275, wordEng: "undergo", wordUA: "піддаватися / проходити через", transcription: "[ˌʌndəˈɡəʊ]"},
  {id: 276, wordEng: "undertake", wordUA: "братися (за справу)", transcription: "[ˌʌndəˈteɪk]"},
  {id: 277, wordEng: "utilize", wordUA: "використовувати / утилізувати", transcription: "[ˈjuːtəlaɪz]"},
  {id: 278, wordEng: "valid", wordUA: "дійсний / обґрунтований", transcription: "[ˈvælɪd]"},
  {id: 279, wordEng: "versatile", wordUA: "універсальний / багатогранний", transcription: "[ˈvɜːsətaɪl]"},
  {id: 280, wordEng: "viable", wordUA: "життєздатний", transcription: "[ˈvaɪəbl]"},
  {id: 281, wordEng: "widespread", wordUA: "широко поширений", transcription: "[ˈwaɪdspred]"},
  {id: 282, wordEng: "yield", wordUA: "поступатися / приносити (результат)", transcription: "[jiːld]"},
  {id: 283, wordEng: "bias", wordUA: "упередження", transcription: "[ˈbaɪəs]"},
  {id: 284, wordEng: "consensus", wordUA: "згода / консенсус", transcription: "[kənˈsensəs]"},
  {id: 285, wordEng: "constraint", wordUA: "обмеження", transcription: "[kənˈstreɪnt]"},
  {id: 286, wordEng: "correlation", wordUA: "взаємозв'язок", transcription: "[ˌkɒrəˈleɪʃn]"},
  {id: 287, wordEng: "diversity", wordUA: "різноманітність", transcription: "[daɪˈvɜːsəti]"},
  {id: 288, wordEng: "efficiency", wordUA: "ефективність", transcription: "[ɪˈfɪʃnsi]"},
  {id: 289, wordEng: "entity", wordUA: "об'єкт / сутність", transcription: "[ˈentəti]"},
  {id: 290, wordEng: "feasibility", wordUA: "доцільність / можливість", transcription: "[ˌfiːzəˈbɪləti]"},
  {id: 291, wordEng: "integrity", wordUA: "цілісність / чесність", transcription: "[ɪnˈteɡrəti]"},
  {id: 292, wordEng: "notion", wordUA: "поняття / уявлення", transcription: "[ˈnəʊʃn]"},
  {id: 293, wordEng: "paradigm", wordUA: "парадигма / модель", transcription: "[ˈpærədaɪm]"},
  {id: 294, wordEng: "precedent", wordUA: "прецедент", transcription: "[ˈpresɪdənt]"},
  {id: 295, wordEng: "priority", wordUA: "пріоритет", transcription: "[praɪˈɒrəti]"},
  {id: 296, wordEng: "quota", wordUA: "квота / частка", transcription: "[ˈkwəʊtə]"},
  {id: 297, wordEng: "resolution", wordUA: "вирішення / резолюція", transcription: "[ˌrezəˈluːʃn]"},
  {id: 298, wordEng: "scheme", wordUA: "схема / план", transcription: "[skiːm]"},
  {id: 299, wordEng: "stability", wordUA: "стабільність", transcription: "[stəˈbɪləti]"},
  {id: 300, wordEng: "status quo", wordUA: "існуючий стан справ", transcription: "[ˌsteɪtəs ˈkwəʊ]"}
];