const beginnerWords = [
  { id: 1, wordEng: "hello", wordUA: "привіт", transcription: "[həˈləʊ]", example: "Hello! How are you today?" },
  { id: 2, wordEng: "thank you", wordUA: "дякую", transcription: "[θæŋk juː]", example: "Thank you for your help." },
  { id: 3, wordEng: "please", wordUA: "будь ласка (прохання)", transcription: "[pliːz]", example: "Open the window, please." },
  { id: 4, wordEng: "you're welcome", wordUA: "будь ласка (відповідь)", transcription: "[jʊə ˈwelkəm]", example: "— Thanks! — You're welcome." },
  { id: 5, wordEng: "excuse me", wordUA: "перепрошую", transcription: "[ɪkˈskjuːz miː]", example: "Excuse me, where is the station?" },
  { id: 6, wordEng: "sorry", wordUA: "вибачте", transcription: "[ˈsɒri]", example: "I am sorry, I am late." },
  { id: 7, wordEng: "yes", wordUA: "так", transcription: "[jes]", example: "Yes, I am a student." },
  { id: 8, wordEng: "no", wordUA: "ні", transcription: "[nəʊ]", example: "No, thank you." },
  { id: 9, wordEng: "maybe", wordUA: "можливо", transcription: "[ˈmeɪbi]", example: "Maybe we can go to the cinema." },
  { id: 10, wordEng: "goodbye", wordUA: "до побачення", transcription: "[ˌɡʊdˈbaɪ]", example: "Goodbye! See you tomorrow." },
  { id: 11, wordEng: "help", wordUA: "допомога", transcription: "[help]", example: "I need your help with this bag." },
  { id: 12, wordEng: "I don't know", wordUA: "я не знаю", transcription: "[aɪ dəʊnt nəʊ]", example: "I don't know the answer." },
  { id: 13, wordEng: "I understand", wordUA: "я розумію", transcription: "[aɪ ˌʌndəˈstænd]", example: "Yes, I understand you now." },
  { id: 14, wordEng: "I don't understand", wordUA: "я не розумію", transcription: "[aɪ dəʊnt ˌʌndəˈstænd]", example: "Sorry, I don't understand English." },
  { id: 15, wordEng: "what", wordUA: "що / який", transcription: "[wɒt]", example: "What is your name?" },
  { id: 16, wordEng: "where", wordUA: "де / куди", transcription: "[weə]", example: "Where is the toilet?" },
  { id: 17, wordEng: "when", wordUA: "коли", transcription: "[wen]", example: "When is your birthday?" },
  { id: 18, wordEng: "why", wordUA: "чому", transcription: "[waɪ]", example: "Why are you sad?" },
  { id: 19, wordEng: "who", wordUA: "хто", transcription: "[huː]", example: "Who is that man?" },
  { id: 20, wordEng: "how", wordUA: "як", transcription: "[haʊ]", example: "How do you spell your name?" },
  { id: 21, wordEng: "how much", wordUA: "скільки (ціна)", transcription: "[haʊ mʌtʃ]", example: "How much is this coffee?" },
  { id: 22, wordEng: "how many", wordUA: "скільки (кількість)", transcription: "[haʊ ˈmeni]", example: "How many brothers do you have?" },
  { id: 23, wordEng: "what time is it", wordUA: "котра година", transcription: "[wɒt taɪm ɪz ɪt]", example: "Excuse me, what time is it?" },
  { id: 24, wordEng: "where is", wordUA: "де знаходиться", transcription: "[weə ɪz]", example: "Where is the nearest bank?" },
  { id: 25, wordEng: "I need", wordUA: "мені потрібно", transcription: "[aɪ niːd]", example: "I need a doctor." },
  { id: 26, wordEng: "I want", wordUA: "я хочу", transcription: "[aɪ wɒnt]", example: "I want an apple juice." },
  { id: 27, wordEng: "I'd like", wordUA: "я б хотів", transcription: "[aɪd laɪk]", example: "I'd like a cup of tea." },
  { id: 28, wordEng: "can I", wordUA: "можна мені / чи можу я", transcription: "[kæn aɪ]", example: "Can I use your phone?" },
  { id: 29, wordEng: "could you", wordUA: "не могли б ви", transcription: "[kʊd juː]", example: "Could you repeat that, please?" },
  { id: 30, wordEng: "give me", wordUA: "дайте мені", transcription: "[ɡɪv miː]", example: "Give me the menu, please." },
  { id: 31, wordEng: "show me", wordUA: "покажіть мені", transcription: "[ʃəʊ miː]", example: "Show me the photos from your trip." },
  { id: 32, wordEng: "wait", wordUA: "чекати", transcription: "[weɪt]", example: "Wait a minute, I am ready." },
  { id: 33, wordEng: "look", wordUA: "дивитися", transcription: "[lʊk]", example: "Look at this beautiful flower." },
  { id: 34, wordEng: "listen", wordUA: "слухати", transcription: "[ˈlɪsn]", example: "Listen to the teacher." },
  { id: 35, wordEng: "stop", wordUA: "зупинитися", transcription: "[stɒp]", example: "Please, stop the car." },
  { id: 36, wordEng: "go", wordUA: "йти / їхати", transcription: "[ɡəʊ]", example: "Let's go to the park." },
  { id: 37, wordEng: "come", wordUA: "приходити", transcription: "[kʌm]", example: "Come here, I want to show you something." },
  { id: 38, wordEng: "eat", wordUA: "їсти", transcription: "[iːt]", example: "I want to eat pizza." },
  { id: 39, wordEng: "drink", wordUA: "пити", transcription: "[drɪŋk]", example: "Would you like something to drink?" },
  { id: 40, wordEng: "sleep", wordUA: "спати", transcription: "[sliːp]", example: "I need to sleep 8 hours." },
  { id: 41, wordEng: "buy", wordUA: "купувати", transcription: "[baɪ]", example: "I want to buy a new phone." },
  { id: 42, wordEng: "sell", wordUA: "продавати", transcription: "[sel]", example: "I want to sell my old car." },
  { id: 43, wordEng: "open", wordUA: "відчинено", transcription: "[ˈəʊpən]", example: "The shop is open now." },
  { id: 44, wordEng: "closed", wordUA: "зачинено", transcription: "[kləʊzd]", example: "I am sorry, we are closed." },
  { id: 45, wordEng: "push", wordUA: "від себе", transcription: "[pʊʃ]", example: "Push the door to enter." },
  { id: 46, wordEng: "pull", wordUA: "на себе", transcription: "[pʊl]", example: "Pull the door to open it." },
  { id: 47, wordEng: "today", wordUA: "сьогодні", transcription: "[təˈdeɪ]", example: "The weather is nice today." },
  { id: 48, wordEng: "tomorrow", wordUA: "завтра", transcription: "[təˈmɒrəʊ]", example: "See you tomorrow morning." },
  { id: 49, wordEng: "yesterday", wordUA: "вчора", transcription: "[ˈjestədeɪ]", example: "Yesterday was a busy day." },
  { id: 50, wordEng: "now", wordUA: "зараз", transcription: "[naʊ]", example: "I am busy right now." },
  { id: 51, wordEng: "later", wordUA: "пізніше", transcription: "[ˈleɪtə]", example: "Call me later, please." },
  { id: 52, wordEng: "always", wordUA: "завжди", transcription: "[ˈɔːlweɪz]", example: "She always drinks coffee in the morning." },
  { id: 53, wordEng: "never", wordUA: "ніколи", transcription: "[ˈnevə]", example: "I never eat meat." },
  { id: 54, wordEng: "often", wordUA: "часто", transcription: "[ˈɒfn]", example: "We often go to the mountains." },
  { id: 55, wordEng: "sometimes", wordUA: "інколи", transcription: "[ˈsʌmtaɪmz]", example: "Sometimes I watch TV in the evening." },
  { id: 56, wordEng: "good", wordUA: "добре / хороший", transcription: "[ɡʊd]", example: "This is a very good book." },
  { id: 57, wordEng: "bad", wordUA: "погано / поганий", transcription: "[bæd]", example: "I have a bad headache." },
  { id: 58, wordEng: "hot", wordUA: "гарячий / жарко", transcription: "[hɒt]", example: "The soup is very hot." },
  { id: 59, wordEng: "cold", wordUA: "холодний / холодно", transcription: "[kəʊld]", example: "It is very cold today." },
  { id: 60, wordEng: "big", wordUA: "великий", transcription: "[bɪɡ]", example: "They live in a big house." },
  { id: 61, wordEng: "small", wordUA: "маленький", transcription: "[smɔːl]", example: "I have a small cat." },
  { id: 62, wordEng: "fast", wordUA: "швидко", transcription: "[fɑːst]", example: "He drives a fast car." },
  { id: 63, wordEng: "slow", wordUA: "повільно", transcription: "[sləʊ]", example: "The internet is very slow." },
  { id: 64, wordEng: "easy", wordUA: "легко", transcription: "[ˈiːzi]", example: "The English test was easy." },
  { id: 65, wordEng: "difficult", wordUA: "важко", transcription: "[ˈdɪfɪkəlt]", example: "This is a difficult question." },
  { id: 66, wordEng: "cheap", wordUA: "дешево", transcription: "[tʃiːp]", example: "The bread is very cheap here." },
  { id: 67, wordEng: "expensive", wordUA: "дорого", transcription: "[ɪkˈspensɪv]", example: "That watch is too expensive." },
  { id: 68, wordEng: "new", wordUA: "новий", transcription: "[njuː]", example: "I bought a new shirt." },
  { id: 69, wordEng: "old", wordUA: "старий", transcription: "[əʊld]", example: "My car is very old." },
  { id: 70, wordEng: "beautiful", wordUA: "красивий", transcription: "[ˈbjuːtɪfl]", example: "What a beautiful sunset!" },
  { id: 71, wordEng: "happy", wordUA: "щасливий", transcription: "[ˈhæpi]", example: "I am so happy to see you." },
  { id: 72, wordEng: "sad", wordUA: "сумний", transcription: "[sæd]", example: "The movie was very sad." },
  { id: 73, wordEng: "tired", wordUA: "втомлений", transcription: "[ˈtaɪəd]", example: "I am tired after work." },
  { id: 74, wordEng: "hungry", wordUA: "голодний", transcription: "[ˈhʌŋɡri]", example: "Are you hungry? Let's eat." },
  { id: 75, wordEng: "thirsty", wordUA: "хоче пити", transcription: "[ˈθɜːsti]", example: "I am thirsty, I need water." },
  { id: 76, wordEng: "ready", wordUA: "готовий", transcription: "[ˈredi]", example: "Are you ready to go?" },
  { id: 77, wordEng: "here", wordUA: "тут", transcription: "[hɪə]", example: "Your keys are here on the table." },
  { id: 78, wordEng: "there", wordUA: "там", transcription: "[ðeə]", example: "Look, the bus is there." },
  { id: 79, wordEng: "left", wordUA: "ліворуч", transcription: "[left]", example: "Turn left at the next corner." },
  { id: 80, wordEng: "right", wordUA: "праворуч / правильно", transcription: "[raɪt]", example: "You are right about that." },
  { id: 81, wordEng: "straight", wordUA: "прямо", transcription: "[streɪt]", example: "Go straight for two blocks." },
  { id: 82, wordEng: "early", wordUA: "рано", transcription: "[ˈɜːli]", example: "I wake up early in the morning." },
  { id: 83, wordEng: "late", wordUA: "пізно", transcription: "[leɪt]", example: "Don't be late for the meeting." },
  { id: 84, wordEng: "very", wordUA: "дуже", transcription: "[ˈveri]", example: "The coffee is very hot." },
  { id: 85, wordEng: "too", wordUA: "занадто / також", transcription: "[tuː]", example: "The soup is too salty." },
  { id: 86, wordEng: "enough", wordUA: "достатньо", transcription: "[ɪˈnʌf]", example: "I have enough money." },
  { id: 87, wordEng: "and", wordUA: "і / та", transcription: "[ænd]", example: "I like tea and coffee." },
  { id: 88, wordEng: "but", wordUA: "але", transcription: "[bʌt]", example: "I am tired but I am happy." },
  { id: 89, wordEng: "or", wordUA: "або", transcription: "[ɔː]", example: "Tea or coffee?" },
  { id: 90, wordEng: "because", wordUA: "тому що", transcription: "[bɪˈkəz]", example: "I am happy because it's Friday." },
  { id: 91, wordEng: "with", wordUA: "з", transcription: "[wɪð]", example: "I live with my parents." },
  { id: 92, wordEng: "without", wordUA: "без", transcription: "[wɪˈðaʊt]", example: "I can't live without my phone." },
  { id: 93, wordEng: "about", wordUA: "про", transcription: "[əˈbaʊt]", example: "Tell me about your family." },
  { id: 94, wordEng: "for", wordUA: "для", transcription: "[fɔː]", example: "This gift is for you." },
  { id: 95, wordEng: "from", wordUA: "від / з", transcription: "[frəm]", example: "I am from Ukraine." },
  { id: 96, wordEng: "to", wordUA: "до / напрямок", transcription: "[tuː]", example: "I am going to the shop." },
  { id: 97, wordEng: "at", wordUA: "в (точці) / біля", transcription: "[æt]", example: "I am at home now." },
  { id: 98, wordEng: "on", wordUA: "на", transcription: "[ɒn]", example: "The book is on the table." },
  { id: 99, wordEng: "in", wordUA: "в (всередині)", transcription: "[ɪn]", example: "The keys are in the bag." },
  { id: 100, wordEng: "by the way", wordUA: "до речі", transcription: "[baɪ ðə weɪ]", example: "By the way, I like your shirt." },
  { id: 101, wordEng: "Burying", wordUA: "поховання / закопування", transcription: "[ˈberiɪŋ]",example: "Burying the treasure in the garden took all afternoon."},
  { id: 102, wordEng: "Clue", wordUA: "ключ / підказка", transcription: "[kluː]", example: "The detective found a clue that led to the suspect."},
  { id: 103, wordEng: "Handwriting", wordUA: "почерк", transcription: "[ˈhændˌraɪtɪŋ]", example: "Her handwriting is very neat and easy to read."},
  { id: 104, wordEng: "Tongue", wordUA: "язик", transcription: "[tʌŋ]", example: "He bit his tongue while trying not to laugh." },
  { id: 105, wordEng: "Rash", wordUA: "висип / необачний", transcription: "[ræʃ]", example: "He made a rash decision without thinking it through."},
  { id: 106, wordEng: "Wide", wordUA: "широкий", transcription: "[waɪd]", example: "The river is very wide at this point." },
  { id: 107, wordEng: "Disgusting", wordUA: "огидний / гидкий", transcription: "[dɪsˈɡʌstɪŋ]", example: "The food was so disgusting that I couldn’t eat it."}
];

const intermediateWords = [
  { id: 101, wordEng: "although", wordUA: "хоча", transcription: "[ɔːlˈðəʊ]", example: "Although it was raining, we went for a walk." },
  { id: 102, wordEng: "however", wordUA: "проте / однак", transcription: "[haʊˈevə]", example: "He is very rich; however, he is not happy." },
  { id: 103, wordEng: "therefore", wordUA: "отже / тому", transcription: "[ˈðeəfɔː]", example: "I forgot my wallet; therefore, I couldn't buy lunch." },
  { id: 104, wordEng: "instead", wordUA: "замість цього", transcription: "[ɪnˈsted]", example: "I didn't go to Paris; instead, I went to Rome." },
  { id: 105, wordEng: "perhaps", wordUA: "можливо / мабуть", transcription: "[pəˈhæps]", example: "Perhaps we should ask for directions." },
  { id: 106, wordEng: "probably", wordUA: "ймовірно", transcription: "[ˈprɒbəbli]", example: "I'll probably stay at home tonight." },
  { id: 107, wordEng: "actually", wordUA: "насправді", transcription: "[ˈæktʃuəli]", example: "Actually, I've never seen that movie before." },
  { id: 108, wordEng: "especially", wordUA: "особливо", transcription: "[ɪˈspeʃəli]", example: "I love sweets, especially chocolate." },
  { id: 109, wordEng: "experience", wordUA: "досвід", transcription: "[ɪkˈspɪəriəns]", example: "Do you have any experience in sales?" },
  { id: 110, wordEng: "opportunity", wordUA: "можливість", transcription: "[ˌɒpəˈtjuːnəti]", example: "Traveling gives you the opportunity to learn." },
  { id: 111, wordEng: "decision", wordUA: "рішення", transcription: "[dɪˈsɪʒn]", example: "It was a very difficult decision to make." },
  { id: 112, wordEng: "agreement", wordUA: "угода / згода", transcription: "[əˈɡriːmənt]", example: "We finally reached an agreement on the price." },
  { id: 113, wordEng: "development", wordUA: "розвиток", transcription: "[dɪˈveləpmənt]", example: "The development of new technology is fast." },
  { id: 114, wordEng: "government", wordUA: "уряд", transcription: "[ˈɡʌvənmənt]", example: "The government is planning new taxes." },
  { id: 115, wordEng: "knowledge", wordUA: "знання", transcription: "[ˈnɒlɪdʒ]", example: "She has a wide knowledge of history." },
  { id: 116, wordEng: "environment", wordUA: "середовище", transcription: "[ɪnˈvaɪrənmənt]", example: "We must protect the natural environment." },
  { id: 117, wordEng: "society", wordUA: "суспільство", transcription: "[səˈsaɪəti]", example: "Living in a society requires following rules." },
  { id: 118, wordEng: "believe", wordUA: "вірити", transcription: "[bɪˈliːv]", example: "I believe that everything will be fine." },
  { id: 119, wordEng: "remember", wordUA: "пам'ятати", transcription: "[rɪˈmembə]", example: "I can't remember where I left my keys." },
  { id: 120, wordEng: "forget", wordUA: "забувати", transcription: "[fəˈɡet]", example: "Don't forget to call your mother." },
  { id: 121, wordEng: "improve", wordUA: "покращувати", transcription: "[ɪmˈpruːv]", example: "I want to improve my English skills." },
  { id: 122, wordEng: "increase", wordUA: "збільшувати", transcription: "[ɪnˈkriːs]", example: "The company wants to increase its sales." },
  { id: 123, wordEng: "decrease", wordUA: "зменшувати", transcription: "[dɪˈkriːs]", example: "We need to decrease our monthly spending." },
  { id: 124, wordEng: "provide", wordUA: "надавати / забезпечувати", transcription: "[prəˈvaɪd]", example: "The hotel provides free breakfast." },
  { id: 125, wordEng: "receive", wordUA: "отримувати", transcription: "[rɪˈsiːv]", example: "I received a letter from my friend today." },
  { id: 126, wordEng: "describe", wordUA: "описувати", transcription: "[dɪˈskraɪb]", example: "Can you describe the person you saw?" },
  { id: 127, wordEng: "explain", wordUA: "пояснювати", transcription: "[ɪkˈspleɪn]", example: "Let me explain why I was late." },
  { id: 128, wordEng: "imagine", wordUA: "уявляти", transcription: "[ɪˈmædʒɪn]", example: "Imagine living on a desert island." },
  { id: 129, wordEng: "suggest", wordUA: "пропонувати / радити", transcription: "[səˈdʒest]", example: "I suggest going to the park today." },
  { id: 130, wordEng: "discuss", wordUA: "обговорювати", transcription: "[dɪˈskʌs]", example: "We need to discuss this problem together." },
  { id: 131, wordEng: "happen", wordUA: "траплятися", transcription: "[ˈhæpən]", example: "What will happen if we don't finish in time?" },
  { id: 132, wordEng: "expect", wordUA: "очікувати", transcription: "[ɪkˈspekt]", example: "I expect to finish the work by Friday." },
  { id: 133, wordEng: "suppose", wordUA: "припускати", transcription: "[səˈpəʊz]", example: "I suppose you are right about this." },
  { id: 134, wordEng: "realize", wordUA: "усвідомлювати", transcription: "[ˈrɪəlaɪz]", example: "I didn't realize how late it was." },
  { id: 135, wordEng: "complain", wordUA: "скаржитися", transcription: "[kəmˈpleɪn]", example: "They always complain about the weather." },
  { id: 136, wordEng: "avoid", wordUA: "уникати", transcription: "[əˈvɔɪd]", example: "You should avoid eating too much sugar." },
  { id: 137, wordEng: "depend", wordUA: "залежати", transcription: "[dɪˈpend]", example: "Our plans depend on the weather." },
  { id: 138, wordEng: "achieve", wordUA: "досягати", transcription: "[əˈtʃiːv]", example: "You can achieve anything if you work hard." },
  { id: 139, wordEng: "refuse", wordUA: "відмовлятися", transcription: "[rɪˈfjuːz]", example: "He refused to answer my question." },
  { id: 140, wordEng: "accept", wordUA: "приймати", transcription: "[əkˈsept]", example: "She accepted the job offer immediately." },
  { id: 141, wordEng: "useful", wordUA: "корисний", transcription: "[ˈjuːsfl]", example: "This book is very useful for beginners." },
  { id: 142, wordEng: "useless", wordUA: "марний", transcription: "[ˈjuːsləs]", example: "This old phone is completely useless now." },
  { id: 143, wordEng: "necessary", wordUA: "необхідний", transcription: "[ˈnesəsəri]", example: "Is it necessary to sign this document?" },
  { id: 144, wordEng: "possible", wordUA: "можливий", transcription: "[ˈpɒsəbl]", example: "Is it possible to change the date?" },
  { id: 145, wordEng: "impossible", wordUA: "неможливий", transcription: "[ɪmˈpɒsəbl]", example: "It's impossible to please everyone." },
  { id: 146, wordEng: "available", wordUA: "доступний", transcription: "[əˈveɪləbl]", example: "Is this dress available in a larger size?" },
  { id: 147, wordEng: "successful", wordUA: "успішний", transcription: "[səkˈsesfl]", example: "The project was very successful." },
  { id: 148, wordEng: "responsible", wordUA: "відповідальний", transcription: "[rɪˈspɒnsəbl]", example: "Who is responsible for this project?" },
  { id: 149, wordEng: "various", wordUA: "різноманітні", transcription: "[ˈveəriəs]", example: "I have lived in various cities." },
  { id: 150, wordEng: "common", wordUA: "спільний / звичайний", transcription: "[ˈkɒmən]", example: "Common sense is not so common." },
  { id: 151, wordEng: "similar", wordUA: "схожий", transcription: "[ˈsɪmələ]", example: "Your house is very similar to mine." },
  { id: 152, wordEng: "different", wordUA: "інший / різний", transcription: "[ˈdɪfrənt]", example: "The two brothers are very different." },
  { id: 153, wordEng: "certain", wordUA: "певний / впевнений", transcription: "[ˈsɜːtn]", example: "Are you certain that he is coming?" },
  { id: 154, wordEng: "careful", wordUA: "обережний", transcription: "[ˈkeəfl]", example: "Be careful when you cross the street." },
  { id: 155, wordEng: "dangerous", wordUA: "небезпечний", transcription: "[ˈdeɪndʒərəs]", example: "It's dangerous to walk here at night." },
  { id: 156, wordEng: "famous", wordUA: "відомий", transcription: "[ˈfeɪməs]", example: "He is a very famous actor." },
  { id: 157, wordEng: "lucky", wordUA: "удачливий", transcription: "[ˈlʌki]", example: "I am lucky to have such good friends." },
  { id: 158, wordEng: "patient", wordUA: "терплячий", transcription: "[ˈpeɪʃnt]", example: "You need to be patient with children." },
  { id: 159, wordEng: "polite", wordUA: "ввічливий", transcription: "[pəˈlaɪt]", example: "It's important to be polite to everyone." },
  { id: 160, wordEng: "rude", wordUA: "грубий", transcription: "[ruːd]", example: "His rude behavior shocked everyone." },
  { id: 161, wordEng: "suddenly", wordUA: "раптом", transcription: "[ˈsʌdənli]", example: "Suddenly, the lights went out." },
  { id: 162, wordEng: "immediately", wordUA: "негайно", transcription: "[ɪˈmiːdiətli]", example: "Please come home immediately." },
  { id: 163, wordEng: "recently", wordUA: "нещодавно", transcription: "[ˈriːsntli]", example: "I haven't seen her recently." },
  { id: 164, wordEng: "completely", wordUA: "повністю", transcription: "[kəmˈpliːtli]", example: "I completely forgot about the meeting." },
  { id: 165, wordEng: "finally", wordUA: "зрештою", transcription: "[ˈfaɪnəli]", example: "Finally, the train arrived." },
  { id: 166, wordEng: "quickly", wordUA: "швидко", transcription: "[ˈkwɪkli]", example: "We need to finish this quickly." },
  { id: 167, wordEng: "slowly", wordUA: "повільно", transcription: "[ˈsləʊli]", example: "Please speak more slowly." },
  { id: 168, wordEng: "hardly", wordUA: "навряд чи", transcription: "[ˈhɑːdli]", example: "I can hardly hear you." },
  { id: 169, wordEng: "enough", wordUA: "достатньо", transcription: "[ɪˈnʌf]", example: "Do we have enough bread for dinner?" },
  { id: 170, wordEng: "already", wordUA: "вже", transcription: "[ɔːlˈredi]", example: "I have already finished my homework." },
  { id: 171, wordEng: "still", wordUA: "все ще", transcription: "[stɪl]", example: "Are you still working at the bank?" },
  { id: 172, wordEng: "yet", wordUA: "ще (в запереченнях)", transcription: "[jet]", example: "I haven't seen that movie yet." },
  { id: 173, wordEng: "since", wordUA: "з того часу як", transcription: "[sɪns]", example: "I haven't eaten anything since breakfast." },
  { id: 174, wordEng: "while", wordUA: "поки / в той час як", transcription: "[waɪl]", example: "The phone rang while I was cooking." },
  { id: 175, wordEng: "during", wordUA: "протягом", transcription: "[ˈdjʊərɪŋ]", example: "I fell asleep during the movie." },
  { id: 176, wordEng: "between", wordUA: "між (двома)", transcription: "[bɪˈtwiːn]", example: "The shop is between the bank and the pharmacy." },
  { id: 177, wordEng: "among", wordUA: "серед (багатьох)", transcription: "[əˈmʌŋ]", example: "She was sitting among her friends." },
  { id: 178, wordEng: "above", wordUA: "над", transcription: "[əˈbʌv]", example: "The plane was flying above the clouds." },
  { id: 179, wordEng: "below", wordUA: "під / нижче", transcription: "[bɪˈləʊ]", example: "The temperature is below zero." },
  { id: 180, wordEng: "against", wordUA: "проти", transcription: "[əˈɡenst]", example: "They played against a very strong team." },
  { id: 181, wordEng: "reason", wordUA: "причина", transcription: "[ˈriːzn]", example: "What is the reason for your delay?" },
  { id: 182, wordEng: "result", wordUA: "результат", transcription: "[rɪˈzʌlt]", example: "The exam results will be out tomorrow." },
  { id: 183, wordEng: "purpose", wordUA: "мета", transcription: "[ˈpɜːpəs]", example: "The purpose of this meeting is to plan the trip." },
  { id: 184, wordEng: "opinion", wordUA: "думка", transcription: "[əˈpɪnjən]", example: "In my opinion, this is the best option." },
  { id: 185, wordEng: "advice", wordUA: "порада", transcription: "[ədˈvaɪs]", example: "Can you give me some advice?" },
  { id: 186, wordEng: "suggestion", wordUA: "пропозиція", transcription: "[səˈdʒestʃən]", example: "Do you have any suggestions for dinner?" },
  { id: 187, wordEng: "solution", wordUA: "рішення (проблеми)", transcription: "[səˈluːʃn]", example: "We need to find a solution to this problem." },
  { id: 188, wordEng: "problem", wordUA: "проблема", transcription: "[ˈprɒbləm]", example: "There is a small problem with the car." },
  { id: 189, wordEng: "difference", wordUA: "різниця", transcription: "[ˈdɪfrəns]", example: "What is the difference between these two?" },
  { id: 190, wordEng: "advantage", wordUA: "перевага", transcription: "[ədˈvɑːntɪdʒ]", example: "Living in a city has many advantages." },
  { id: 191, wordEng: "disadvantage", wordUA: "недолік", transcription: "[ˌdɪsədˈvɑːntɪdʒ]", example: "The main disadvantage is the high cost." },
  { id: 192, wordEng: "ability", wordUA: "здатність", transcription: "[əˈbɪləti]", example: "He has the ability to learn languages quickly." },
  { id: 193, wordEng: "behavior", wordUA: "поведінка", transcription: "[bɪˈheɪvjə]", example: "His behavior at school was excellent." },
  { id: 194, wordEng: "celebration", wordUA: "святкування", transcription: "[ˌselɪˈbreɪʃn]", example: "The birthday celebration lasted all night." },
  { id: 195, wordEng: "condition", wordUA: "умова / стан", transcription: "[kənˈdɪʃn]", example: "The car is in very good condition." },
  { id: 196, wordEng: "education", wordUA: "освіта", transcription: "[ˌedʒuˈkeɪʃn]", example: "Education is very important for your future." },
  { id: 197, wordEng: "health", wordUA: "здоров'я", transcription: "[helθ]", example: "Fruit is good for your health." },
  { id: 198, wordEng: "island", wordUA: "острів", transcription: "[ˈaɪlənd]", example: "They spent their holiday on a tropical island." },
  { id: 199, wordEng: "journey", wordUA: "подорож", transcription: "[ˈdʒɜːni]", example: "The journey across the desert took three days." },
  { id: 200, wordEng: "neighborhood", wordUA: "сусідство / район", transcription: "[ˈneɪbəhʊd]", example: "It's a very quiet and safe neighborhood." }
];

const advancedWords = [
  { id: 201, wordEng: "ambiguous", wordUA: "двозначний / неясний", transcription: "[æmˈbɪɡjuəs]", example: "His reply was ambiguous, and we didn't know his real intentions." },
  { id: 202, wordEng: "comprehensive", wordUA: "вичерпний / всебічний", transcription: "[ˌkɒmprɪˈhensɪv]", example: "The company provides a comprehensive insurance policy for all employees." },
  { id: 203, wordEng: "consequence", wordUA: "наслідок", transcription: "[ˈkɒnsɪkwəns]", example: "Every action has a consequence that you must be prepared for." },
  { id: 204, wordEng: "controversial", wordUA: "суперечливий", transcription: "[ˌkɒntrəˈvɜːʃl]", example: "The mayor's decision to close the park was highly controversial." },
  { id: 205, wordEng: "crucial", wordUA: "вирішальний / критичний", transcription: "[ˈkruːʃl]", example: "Vitamins play a crucial role in maintaining good health." },
  { id: 206, wordEng: "distinction", wordUA: "відмінність / розрізнення", transcription: "[dɪˈstɪŋkʃn]", example: "There is a clear distinction between these two types of engines." },
  { id: 207, wordEng: "elaborate", wordUA: "детально розробляти", transcription: "[ɪˈlæbərət]", example: "Please elaborate on your proposal during the next meeting." },
  { id: 208, wordEng: "hypothesis", wordUA: "гіпотеза", transcription: "[haɪˈpɒθəsɪs]", example: "Scientists are testing the hypothesis to see if it holds true." },
  { id: 209, wordEng: "implement", wordUA: "впроваджувати", transcription: "[ˈɪmplɪment]", example: "The government plans to implement new safety regulations next month." },
  { id: 210, wordEng: "inevitable", wordUA: "неминучий", transcription: "[ɪnˈevɪtəbl]", example: "If the conflict continues, a war seems inevitable." },
  { id: 211, wordEng: "insight", wordUA: "розуміння суті / осяяння", transcription: "[ˈɪnsaɪt]", example: "The book provides deep insight into the local culture." },
  { id: 212, wordEng: "justify", wordUA: "виправдовувати / обґрунтовувати", transcription: "[ˈdʒʌstɪfaɪ]", example: "It is hard to justify the high cost of this project." },
  { id: 213, wordEng: "obvious", wordUA: "очевидний", transcription: "[ˈɒbviəs]", example: "It was obvious that she was unhappy with the results." },
  { id: 214, wordEng: "perception", wordUA: "сприйняття", transcription: "[pəˈsepʃn]", example: "The public perception of the company has improved recently." },
  { id: 215, wordEng: "redundant", wordUA: "надлишковий / зайвий", transcription: "[rɪˈdʌndənt]", example: "The extra paragraph in your essay is redundant and should be removed." },
  { id: 216, wordEng: "subtle", wordUA: "тонкий / ледь помітний", transcription: "[ˈsʌtl]", example: "There are subtle differences between the original and the copy." },
  { id: 217, wordEng: "sustainable", wordUA: "сталий / життєздатний", transcription: "[səˈsteɪnəbl]", example: "We need to find more sustainable ways to use our resources." },
  { id: 218, wordEng: "vague", wordUA: "нечіткий / розпливчастий", transcription: "[veɪɡ]", example: "She gave a vague answer because she didn't want to commit." },
  { id: 219, wordEng: "vulnerable", wordUA: "вразливий", transcription: "[ˈvʌlnərəbl]", example: "Older people are especially vulnerable to the flu." },
  { id: 220, wordEng: "acknowledge", wordUA: "визнавати / підтверджувати", transcription: "[əkˈnɒlɪdʒ]", example: "I acknowledge that I made a mistake in the report." },
  { id: 221, wordEng: "acquire", wordUA: "набувати / здобувати", transcription: "[əˈkwaɪə]", example: "The company aims to acquire new customers through advertising." },
  { id: 222, wordEng: "advocate", wordUA: "виступати на захист", transcription: "[ˈædvəkeɪt]", example: "They advocate for better working conditions for all staff." },
  { id: 223, wordEng: "allocate", wordUA: "розподіляти (ресурси)", transcription: "[ˈæləkeɪt]", example: "The board must allocate funds for the new research department." },
  { id: 224, wordEng: "anticipate", wordUA: "передбачати", transcription: "[ænˈtɪsɪpeɪt]", example: "We anticipate that the price of gold will rise next year." },
  { id: 225, wordEng: "assert", wordUA: "стверджувати", transcription: "[əˈsɜːt]", example: "You need to assert your authority if you want them to listen." },
  { id: 226, wordEng: "cease", wordUA: "припиняти", transcription: "[siːs]", example: "The factory will cease production at the end of the year." },
  { id: 227, wordEng: "coincide", wordUA: "збігатися", transcription: "[ˌkəʊɪnˈsaɪd]", example: "My holiday doesn't coincide with my wife's vacation." },
  { id: 228, wordEng: "compel", wordUA: "примушувати", transcription: "[kəmˈpel]", example: "The law can compel you to testify in court." },
  { id: 229, wordEng: "concede", wordUA: "поступатися / визнавати поразку", transcription: "[kənˈsiːd]", example: "After counting the votes, the candidate had to concede defeat." },
  { id: 230, wordEng: "deduce", wordUA: "робити висновок", transcription: "[dɪˈdjuːs]", example: "From the evidence, we can deduce that the fire was accidental." },
  { id: 231, wordEng: "depict", wordUA: "зображувати", transcription: "[dɪˈpɪkt]", example: "The painting depicts a scene from the 18th century." },
  { id: 232, wordEng: "deteriorate", wordUA: "погіршуватися", transcription: "[dɪˈtɪəriəreɪt]", example: "If you don't fix the roof, the condition of the house will deteriorate." },
  { id: 233, wordEng: "disrupt", wordUA: "підривати / порушувати", transcription: "[dɪsˈrʌpt]", example: "Protesters tried to disrupt the international conference." },
  { id: 234, wordEng: "eliminate", wordUA: "усувати / ліквідувати", transcription: "[ɪˈlɪmɪneɪt]", example: "We need to eliminate errors to improve our productivity." },
  { id: 235, wordEng: "emphasize", wordUA: "наголошувати", transcription: "[ˈemfəsaɪz]", example: "I want to emphasize the importance of teamwork." },
  { id: 236, wordEng: "encounter", wordUA: "стикатися / несподівано зустріти", transcription: "[ɪnˈkʊntə]", example: "We might encounter some problems during the installation." },
  { id: 237, wordEng: "enhance", wordUA: "посилювати / покращувати", transcription: "[ɪnˈhɑːns]", example: "These improvements will enhance the value of the property." },
  { id: 238, wordEng: "evaluate", wordUA: "оцінювати", transcription: "[ɪˈvæljueɪt]", example: "The teacher will evaluate your progress at the end of the term." },
  { id: 239, wordEng: "exacerbate", wordUA: "загострювати / погіршувати", transcription: "[ɪɡˈzæsəbeɪt]", example: "The new tax will only exacerbate the economic crisis." },
  { id: 240, wordEng: "exceed", wordUA: "перевищувати", transcription: "[ɪkˈsiːd]", example: "The final cost must not exceed the original budget." },
  { id: 241, wordEng: "facilitate", wordUA: "сприяти / полегшувати", transcription: "[fəˈsɪlɪteɪt]", example: "The new software will facilitate faster communication between teams." },
  { id: 242, wordEng: "fluctuate", wordUA: "коливатися", transcription: "[ˈflʌktʃueɪt]", example: "Stock prices fluctuate daily based on market news." },
  { id: 243, wordEng: "foster", wordUA: "сприяти розвитку / виховувати", transcription: "[ˈfɒstə]", example: "The school aims to foster a creative environment for students." },
  { id: 244, wordEng: "hinder", wordUA: "перешкоджати", transcription: "[ˈhɪndə]", example: "A lack of funds will hinder the progress of our research." },
  { id: 245, wordEng: "infer", wordUA: "робити висновок", transcription: "[ɪnˈfɜː]", example: "From his tone, I could infer that he was very angry." },
  { id: 246, wordEng: "inhibit", wordUA: "гальмувати / пригнічувати", transcription: "[ɪnˈhɪbɪt]", example: "Fear of failure can inhibit your ability to succeed." },
  { id: 247, wordEng: "initiate", wordUA: "започатковувати", transcription: "[ɪˈnɪʃieɪt]", example: "The company will initiate a new marketing campaign next week." },
  { id: 248, wordEng: "integrate", wordUA: "об'єднувати", transcription: "[ˈɪntɪɡreɪt]", example: "The aim is to integrate the new system with the existing one." },
  { id: 249, wordEng: "interpret", wordUA: "тлумачити", transcription: "[ɪnˈtɜːprɪt]", example: "It is difficult to interpret the meaning of this old poem." },
  { id: 250, wordEng: "manipulate", wordUA: "маніпулювати", transcription: "[məˈnɪpjuleɪt]", example: "He tried to manipulate the data to get the results he wanted." },
  { id: 251, wordEng: "modify", wordUA: "змінювати / модифікувати", transcription: "[ˈmɒdɪfaɪ]", example: "We had to modify our plans due to the bad weather." },
  { id: 252, wordEng: "notwithstanding", wordUA: "незважаючи на", transcription: "[ˌnɒtwɪθˈstændɪŋ]", example: "Notwithstanding the high price, the product sold very well." },
  { id: 253, wordEng: "obscure", wordUA: "робити неясним / приховувати", transcription: "[əbˈskjʊə]", example: "Technical jargon can often obscure the simple truth." },
  { id: 254, wordEng: "overlook", wordUA: "не помічати / пропускати", transcription: "[ˌəʊvəˈlʊk]", example: "It is easy to overlook small details when you are in a hurry." },
  { id: 255, wordEng: "perceive", wordUA: "сприймати / відчувати", transcription: "[pəˈsiːv]", example: "Cats can perceive movements that humans cannot see." },
  { id: 256, wordEng: "persist", wordUA: "наполегливо продовжувати", transcription: "[pəˈsɪst]", example: "If the pain persists, you should see a doctor." },
  { id: 257, wordEng: "precede", wordUA: "передувати", transcription: "[prɪˈsiːd]", example: "A short introduction will precede the main presentation." },
  { id: 258, wordEng: "prohibit", wordUA: "забороняти", transcription: "[prəˈhɪbɪt]", example: "Smoking is strictly prohibited in this building." },
  { id: 259, wordEng: "pursue", wordUA: "переслідувати / домагатися", transcription: "[pəˈsjuː]", example: "She decided to pursue a career in international law." },
  { id: 260, wordEng: "reconcile", wordUA: "примирити / узгодити", transcription: "[ˈrekənsaɪl]", example: "It's hard to reconcile your lifestyle with your small income." },
  { id: 261, wordEng: "reinforce", wordUA: "підсилювати", transcription: "[ˌriːɪnˈfɔːs]", example: "The latest news only serves to reinforce my opinion." },
  { id: 262, wordEng: "reluctant", wordUA: "неохочий", transcription: "[rɪˈlʌktənt]", example: "He was reluctant to share his secret with anyone." },
  { id: 263, wordEng: "resemble", wordUA: "бути схожим на", transcription: "[rɪˈzembl]", example: "The new building resembles a giant glass pyramid." },
  { id: 264, wordEng: "retain", wordUA: "утримувати / зберігати", transcription: "[rɪˈteɪn]", example: "The company managed to retain its most talented employees." },
  { id: 265, wordEng: "reveal", wordUA: "виявляти / розкривати", transcription: "[rɪˈviːl]", example: "The investigation revealed a series of financial errors." },
  { id: 266, wordEng: "scrutinize", wordUA: "ретельно вивчати", transcription: "[ˈskruːtənaɪz]", example: "Experts will scrutinize the documents to check for fraud." },
  { id: 267, wordEng: "simultaneous", wordUA: "одночасний", transcription: "[ˌsɪmlˈteɪniəs]", example: "The movie will have a simultaneous release in ten countries." },
  { id: 268, wordEng: "speculate", wordUA: "міркувати / робити припущення", transcription: "[ˈspekjuleɪt]", example: "We can only speculate about the reasons for his resignation." },
  { id: 269, wordEng: "subsequent", wordUA: "наступний / подальший", transcription: "[ˈsʌbsɪkwənt]", example: "Subsequent events proved that our initial plan was correct." },
  { id: 270, wordEng: "sufficient", wordUA: "достатній", transcription: "[səˈfɪʃnt]", example: "The police had sufficient evidence to arrest the suspect." },
  { id: 271, wordEng: "surpass", wordUA: "перевершувати", transcription: "[səˈpɑːs]", example: "This year's profits are expected to surpass last year's." },
  { id: 272, wordEng: "sustain", wordUA: "підтримувати", transcription: "[səˈsteɪn]", example: "It's difficult to sustain a long-distance relationship." },
  { id: 273, wordEng: "tedious", wordUA: "нудний / виснажливий", transcription: "[ˈtiːdiəs]", example: "The data entry job was extremely tedious and boring." },
  { id: 274, wordEng: "thrive", wordUA: "процвітати", transcription: "[θraɪv]", example: "Some plants thrive in direct sunlight, while others prefer shade." },
  { id: 275, wordEng: "undergo", wordUA: "піддаватися / проходити через", transcription: "[ˌʌndəˈɡəʊ]", example: "The airport will undergo major renovations next summer." },
  { id: 276, wordEng: "undertake", wordUA: "братися (за справу)", transcription: "[ˌʌndəˈteɪk]", example: "The university will undertake a study on climate change." },
  { id: 277, wordEng: "utilize", wordUA: "використовувати / утилізувати", transcription: "[ˈjuːtəlaɪz]", example: "We must utilize all available resources to solve this problem." },
  { id: 278, wordEng: "valid", wordUA: "дійсний / обґрунтований", transcription: "[ˈvælɪd]", example: "Your passport is valid for another five years." },
  { id: 279, wordEng: "versatile", wordUA: "універсальний / багатогранний", transcription: "[ˈvɜːsətaɪl]", example: "This tool is very versatile and can be used for many tasks." },
  { id: 280, wordEng: "viable", wordUA: "життєздатний", transcription: "[ˈvaɪəbl]", example: "Is this business model viable in the current market?" },
  { id: 281, wordEng: "widespread", wordUA: "широко поширений", transcription: "[ˈwaɪdspred]", example: "There is widespread concern about the new law." },
  { id: 282, wordEng: "yield", wordUA: "поступатися / приносити (результат)", transcription: "[jiːld]", example: "The investment is expected to yield a high profit." },
  { id: 283, wordEng: "bias", wordUA: "упередження", transcription: "[ˈbaɪəs]", example: "The journalist was accused of political bias." },
  { id: 284, wordEng: "consensus", wordUA: "згода / консенсус", transcription: "[kənˈsensəs]", example: "After hours of debate, the committee reached a consensus." },
  { id: 285, wordEng: "constraint", wordUA: "обмеження", transcription: "[kənˈstreɪnt]", example: "Time constraints made it impossible to finish the project." },
  { id: 286, wordEng: "correlation", wordUA: "взаємозв'язок", transcription: "[ˌkɒrəˈleɪʃn]", example: "There is a direct correlation between smoking and lung cancer." },
  { id: 287, wordEng: "diversity", wordUA: "різноманітність", transcription: "[daɪˈvɜːsəti]", example: "The city is known for its cultural diversity." },
  { id: 288, wordEng: "efficiency", wordUA: "ефективність", transcription: "[ɪˈfɪʃnsi]", example: "We need to improve the efficiency of our production line." },
  { id: 289, wordEng: "entity", wordUA: "об'єкт / сутність", transcription: "[ˈentəti]", example: "The two companies merged into a single legal entity." },
  { id: 290, wordEng: "feasibility", wordUA: "доцільність / можливість", transcription: "[ˌfiːzəˈbɪləti]", example: "The feasibility study showed that the project is possible." },
  { id: 291, wordEng: "integrity", wordUA: "цілісність / чесність", transcription: "[ɪnˈteɡrəti]", example: "He is a man of high integrity and can be trusted." },
  { id: 292, wordEng: "notion", wordUA: "поняття / уявлення", transcription: "[ˈnəʊʃn]", example: "The notion that the earth is flat was debunked centuries ago." },
  { id: 293, wordEng: "paradigm", wordUA: "парадигма / модель", transcription: "[ˈpærədaɪm]", example: "The new discovery caused a paradigm shift in physics." },
  { id: 294, wordEng: "precedent", wordUA: "прецедент", transcription: "[ˈpresɪdənt]", example: "This legal case will set a precedent for future rulings." },
  { id: 295, wordEng: "priority", wordUA: "пріоритет", transcription: "[praɪˈɒrəti]", example: "Our first priority is to ensure the safety of our customers." },
  { id: 296, wordEng: "quota", wordUA: "квота / частка", transcription: "[ˈkwəʊtə]", example: "The country has a quota on the amount of imported grain." },
  { id: 297, wordEng: "resolution", wordUA: "вирішення / резолюція", transcription: "[ˌrezəˈluːʃn]", example: "The UN passed a resolution demanding a ceasefire." },
  { id: 298, wordEng: "scheme", wordUA: "схема / план", transcription: "[skiːm]", example: "The government has introduced a new pension scheme." },
  { id: 299, wordEng: "stability", wordUA: "стабільність", transcription: "[stəˈbɪləti]", example: "Economic stability is essential for growth." },
  { id: 300, wordEng: "status quo", wordUA: "існуючий стан справ", transcription: "[ˌsteɪtəs ˈkwəʊ]", example: "Conservatives often want to maintain the status quo." }
];